export let questionsData = [
  {
    id: 1,
    topicId: 1,
    content: "What was the best year?",
    type: "SingleChoice",
    displayVertically: true,
    answers: ["1984", "2005", "2019", "1782"],
    tags: ["year", "subjective"],
    carrectAnswer: ["1984"],
    allowExplanation: false,
  },
  {
    id: 2,
    topicId: 1,
    content: "Where is Waldo?",
    type: "SingleChoice",
    displayVertically: false,
    answers: ["there", "no, hes over there", "right here", "there2"],
    tags: ["Waldo"],
    carrectAnswer: ["there2"],
    allowExplanation: false,
  },
  {
    id: 3,
    topicId: 2,
    content: "How has your day been?",
    type: "MultipleChoice",
    displayVertically: true,
    answers: ["Good", "Alright", "Fine", "Awful"],
    tags: ["Care", "Mood"],
    carrectAnswer: ["Alright", "Fine"],
    allowExplanation: true,
  },
];
